[package]
name = "hackathon2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.2"
pest_derive = "2.7.2"
pyro = "0.2.5"
